"""Add source and created_at fields to Interface model

Revision ID: 23563650d9cd
Revises: 4cc5e53b0c2d
Create Date: 2025-09-29 04:52:28.333589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23563650d9cd'
down_revision = '4cc5e53b0c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        # Add source column as nullable first, then update all rows and make it NOT NULL
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Update all existing rows to have 'collected' as source and current timestamp as created_at
    op.execute("UPDATE interfaces SET source = 'collected' WHERE source IS NULL")
    op.execute("UPDATE interfaces SET created_at = last_updated WHERE created_at IS NULL")

    # Now make source column NOT NULL
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.alter_column('source', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
