"""Remove username_encrypted, password_encrypted, port, device_type, and group_id from Device model

Revision ID: 4cc5e53b0c2d
Revises: 
Create Date: 2025-09-28 17:14:33.028100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc5e53b0c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        # Drop foreign key constraint first by dropping the column that has it
        batch_op.drop_column('group_id')
        batch_op.drop_column('device_type')
        batch_op.drop_column('port')
        batch_op.drop_column('password_encrypted')
        batch_op.drop_column('username_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_encrypted', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('password_encrypted', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('port', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'device_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
